const rockInfo_dict = [
  { name: 'rock_img/I_Andesite_01.jpg', width: 800, height: 587 },
  { name: 'rock_img/I_Andesite_02.jpg', width: 800, height: 850 },
  { name: 'rock_img/I_Andesite_03.jpg', width: 800, height: 573 },
  { name: 'rock_img/I_Andesite_04.jpg', width: 800, height: 596 },
  { name: 'rock_img/I_Andesite_05.jpg', width: 800, height: 412 },
  { name: 'rock_img/I_Andesite_06.jpg', width: 800, height: 684 },
  { name: 'rock_img/I_Andesite_07.jpg', width: 800, height: 593 },
  { name: 'rock_img/I_Andesite_09.jpg', width: 800, height: 600 },
  { name: 'rock_img/I_Andesite_10.jpg', width: 800, height: 416 },
  { name: 'rock_img/I_Andesite_11.jpg', width: 800, height: 492 },
  { name: 'rock_img/I_Andesite_14.jpg', width: 800, height: 545 },
  { name: 'rock_img/I_Andesite_16.jpg', width: 800, height: 601 },
  { name: 'rock_img/I_Basalt_01.jpg', width: 800, height: 788 },
  { name: 'rock_img/I_Basalt_02.jpg', width: 800, height: 645 },
  { name: 'rock_img/I_Basalt_04.jpg', width: 800, height: 753 },
  { name: 'rock_img/I_Basalt_05.jpg', width: 800, height: 818 },
  { name: 'rock_img/I_Basalt_06.jpg', width: 800, height: 706 },
  { name: 'rock_img/I_Basalt_08.jpg', width: 800, height: 1044 },
  { name: 'rock_img/I_Basalt_09.jpg', width: 800, height: 620 },
  { name: 'rock_img/I_Basalt_10.jpg', width: 800, height: 585 },
  { name: 'rock_img/I_Basalt_11.jpg', width: 800, height: 536 },
  { name: 'rock_img/I_Basalt_12.jpg', width: 800, height: 601 },
  { name: 'rock_img/I_Basalt_14.jpg', width: 800, height: 582 },
  { name: 'rock_img/I_Basalt_16.jpg', width: 800, height: 766 },
  { name: 'rock_img/I_Diorite_02.jpg', width: 800, height: 627 },
  { name: 'rock_img/I_Diorite_06.jpg', width: 800, height: 603 },
  { name: 'rock_img/I_Diorite_07.jpg', width: 800, height: 524 },
  { name: 'rock_img/I_Diorite_08.jpg', width: 800, height: 637 },
  { name: 'rock_img/I_Diorite_09.jpg', width: 800, height: 527 },
  { name: 'rock_img/I_Diorite_10.jpg', width: 800, height: 595 },
  { name: 'rock_img/I_Diorite_11.jpg', width: 800, height: 711 },
  { name: 'rock_img/I_Diorite_12.jpg', width: 800, height: 488 },
  { name: 'rock_img/I_Diorite_13.jpg', width: 800, height: 629 },
  { name: 'rock_img/I_Diorite_14.jpg', width: 800, height: 571 },
  { name: 'rock_img/I_Diorite_15.jpg', width: 800, height: 554 },
  { name: 'rock_img/I_Diorite_16.jpg', width: 800, height: 674 },
  { name: 'rock_img/I_Gabbro_01.jpg', width: 800, height: 521 },
  { name: 'rock_img/I_Gabbro_03.jpg', width: 800, height: 852 },
  { name: 'rock_img/I_Gabbro_05.jpg', width: 800, height: 600 },
  { name: 'rock_img/I_Gabbro_08.jpg', width: 800, height: 515 },
  { name: 'rock_img/I_Gabbro_09.jpg', width: 800, height: 728 },
  { name: 'rock_img/I_Gabbro_10.jpg', width: 800, height: 568 },
  { name: 'rock_img/I_Gabbro_11.jpg', width: 800, height: 620 },
  { name: 'rock_img/I_Gabbro_12.jpg', width: 800, height: 780 },
  { name: 'rock_img/I_Gabbro_13.jpg', width: 800, height: 508 },
  { name: 'rock_img/I_Gabbro_14.jpg', width: 800, height: 848 },
  { name: 'rock_img/I_Gabbro_15.jpg', width: 800, height: 629 },
  { name: 'rock_img/I_Gabbro_16.jpg', width: 800, height: 644 },
  { name: 'rock_img/I_Obsidian_02.jpg', width: 800, height: 751 },
  { name: 'rock_img/I_Obsidian_04.jpg', width: 800, height: 693 },
  { name: 'rock_img/I_Obsidian_05.jpg', width: 800, height: 633 },
  { name: 'rock_img/I_Obsidian_06.jpg', width: 800, height: 680 },
  { name: 'rock_img/I_Obsidian_07.jpg', width: 800, height: 476 },
  { name: 'rock_img/I_Obsidian_08.jpg', width: 800, height: 739 },
  { name: 'rock_img/I_Obsidian_09.jpg', width: 800, height: 500 },
  { name: 'rock_img/I_Obsidian_10.jpg', width: 800, height: 626 },
  { name: 'rock_img/I_Obsidian_11.jpg', width: 800, height: 605 },
  { name: 'rock_img/I_Obsidian_12.jpg', width: 800, height: 653 },
  { name: 'rock_img/I_Obsidian_14.jpg', width: 800, height: 764 },
  { name: 'rock_img/I_Obsidian_16.jpg', width: 800, height: 930 },
  { name: 'rock_img/I_Pegmatite_03.jpg', width: 800, height: 524 },
  { name: 'rock_img/I_Pegmatite_05.jpg', width: 800, height: 730 },
  { name: 'rock_img/I_Pegmatite_06.jpg', width: 800, height: 517 },
  { name: 'rock_img/I_Pegmatite_07.jpg', width: 800, height: 670 },
  { name: 'rock_img/I_Pegmatite_08.jpg', width: 800, height: 768 },
  { name: 'rock_img/I_Pegmatite_09.jpg', width: 800, height: 403 },
  { name: 'rock_img/I_Pegmatite_10.jpg', width: 800, height: 416 },
  { name: 'rock_img/I_Pegmatite_11.jpg', width: 800, height: 814 },
  { name: 'rock_img/I_Pegmatite_12.jpg', width: 800, height: 570 },
  { name: 'rock_img/I_Pegmatite_13.jpg', width: 800, height: 495 },
  { name: 'rock_img/I_Pegmatite_15.jpg', width: 800, height: 600 },
  { name: 'rock_img/I_Pegmatite_16.jpg', width: 800, height: 580 },
  { name: 'rock_img/I_Peridotite_02.jpg', width: 800, height: 586 },
  { name: 'rock_img/I_Peridotite_04.jpg', width: 800, height: 668 },
  { name: 'rock_img/I_Peridotite_05.jpg', width: 800, height: 715 },
  { name: 'rock_img/I_Peridotite_06.jpg', width: 800, height: 753 },
  { name: 'rock_img/I_Peridotite_07.jpg', width: 800, height: 483 },
  { name: 'rock_img/I_Peridotite_08.jpg', width: 800, height: 670 },
  { name: 'rock_img/I_Peridotite_10.jpg', width: 800, height: 539 },
  { name: 'rock_img/I_Peridotite_12.jpg', width: 800, height: 454 },
  { name: 'rock_img/I_Peridotite_13.jpg', width: 800, height: 758 },
  { name: 'rock_img/I_Peridotite_14.jpg', width: 800, height: 530 },
  { name: 'rock_img/I_Peridotite_15.jpg', width: 800, height: 600 },
  { name: 'rock_img/I_Peridotite_16.jpg', width: 800, height: 699 },
  { name: 'rock_img/I_Pumice_02.jpg', width: 800, height: 740 },
  { name: 'rock_img/I_Pumice_03.jpg', width: 800, height: 664 },
  { name: 'rock_img/I_Pumice_04.jpg', width: 800, height: 682 },
  { name: 'rock_img/I_Pumice_05.jpg', width: 800, height: 725 },
  { name: 'rock_img/I_Pumice_06.jpg', width: 800, height: 694 },
  { name: 'rock_img/I_Pumice_08.jpg', width: 800, height: 667 },
  { name: 'rock_img/I_Pumice_09.jpg', width: 800, height: 644 },
  { name: 'rock_img/I_Pumice_10.jpg', width: 800, height: 761 },
  { name: 'rock_img/I_Pumice_13.jpg', width: 800, height: 820 },
  { name: 'rock_img/I_Pumice_14.jpg', width: 800, height: 639 },
  { name: 'rock_img/I_Pumice_15.jpg', width: 800, height: 786 },
  { name: 'rock_img/I_Pumice_16.jpg', width: 800, height: 679 }
];

const instructions_image = ['Instructions/demo_cat_selection_CCP1.png', 
                            'Instructions/demo_cat_selection_CCP2.png',
                            'Instructions/demo_cat_selection_GCP.png',
                            'Instructions/demo_class_response.png',
                            'Instructions/demo_paired_cat_display1.png',
                            'Instructions/demo_paired_cat_display2.png'
];

const confusion_dict = [
    {ref:"Andesite",pair:"Andesite",distance:1.08,similarity:0.6318},
    {ref:"Andesite",pair:"Basalt",distance:1.3578,similarity:0.5625},
    {ref:"Andesite",pair:"Diorite",distance:1.891,similarity:0.452},
    {ref:"Andesite",pair:"Gabbro",distance:1.3414,similarity:0.5576},
    {ref:"Andesite",pair:"Obsidian",distance:1.1253,similarity:0.6095},
    {ref:"Andesite",pair:"Pegmatite",distance:1.9115,similarity:0.4583},
    {ref:"Andesite",pair:"Peridotite",distance:1.2016,similarity:0.5919},
    {ref:"Andesite",pair:"Pumice",distance:1.0681,similarity:0.6322},
    {ref:"Basalt",pair:"Andesite",distance:1.3578,similarity:0.5625},
    {ref:"Basalt",pair:"Basalt",distance:1.4735,similarity:0.5668},
    {ref:"Basalt",pair:"Diorite",distance:1.9788,similarity:0.448},
    {ref:"Basalt",pair:"Gabbro",distance:1.4726,similarity:0.5464},
    {ref:"Basalt",pair:"Obsidian",distance:1.2952,similarity:0.586},
    {ref:"Basalt",pair:"Pegmatite",distance:2.0322,similarity:0.4404},
    {ref:"Basalt",pair:"Peridotite",distance:1.3757,similarity:0.5699},
    {ref:"Basalt",pair:"Pumice",distance:1.353,similarity:0.5659},
    {ref:"Diorite",pair:"Andesite",distance:1.891,similarity:0.452},
    {ref:"Diorite",pair:"Basalt",distance:1.9788,similarity:0.448},
    {ref:"Diorite",pair:"Diorite",distance:1.063,similarity:0.6358},
    {ref:"Diorite",pair:"Gabbro",distance:1.2245,similarity:0.5853},
    {ref:"Diorite",pair:"Obsidian",distance:1.4321,similarity:0.5345},
    {ref:"Diorite",pair:"Pegmatite",distance:1.2979,similarity:0.586},
    {ref:"Diorite",pair:"Peridotite",distance:1.8609,similarity:0.4646},
    {ref:"Diorite",pair:"Pumice",distance:2.3954,similarity:0.3558},
    {ref:"Gabbro",pair:"Andesite",distance:1.3414,similarity:0.5576},
    {ref:"Gabbro",pair:"Basalt",distance:1.4726,similarity:0.5464},
    {ref:"Gabbro",pair:"Diorite",distance:1.2245,similarity:0.5853},
    {ref:"Gabbro",pair:"Gabbro",distance:0.9207,similarity:0.6695},
    {ref:"Gabbro",pair:"Obsidian",distance:0.9639,similarity:0.6527},
    {ref:"Gabbro",pair:"Pegmatite",distance:1.3731,similarity:0.5592},
    {ref:"Gabbro",pair:"Peridotite",distance:1.2898,similarity:0.5879},
    {ref:"Gabbro",pair:"Pumice",distance:1.6765,similarity:0.4835},
    {ref:"Obsidian",pair:"Andesite",distance:1.1253,similarity:0.6095},
    {ref:"Obsidian",pair:"Basalt",distance:1.2952,similarity:0.586},
    {ref:"Obsidian",pair:"Diorite",distance:1.4321,similarity:0.5345},
    {ref:"Obsidian",pair:"Gabbro",distance:0.9639,similarity:0.6527},
    {ref:"Obsidian",pair:"Obsidian",distance:0.823,similarity:0.7007},
    {ref:"Obsidian",pair:"Pegmatite",distance:1.5486,similarity:0.5126},
    {ref:"Obsidian",pair:"Peridotite",distance:1.1124,similarity:0.6261},
    {ref:"Obsidian",pair:"Pumice",distance:1.3339,similarity:0.5606},
    {ref:"Pegmatite",pair:"Andesite",distance:1.9115,similarity:0.4583},
    {ref:"Pegmatite",pair:"Basalt",distance:2.0322,similarity:0.4404},
    {ref:"Pegmatite",pair:"Diorite",distance:1.2979,similarity:0.586},
    {ref:"Pegmatite",pair:"Gabbro",distance:1.3731,similarity:0.5592},
    {ref:"Pegmatite",pair:"Obsidian",distance:1.5486,similarity:0.5126},
    {ref:"Pegmatite",pair:"Pegmatite",distance:1.4655,similarity:0.562},
    {ref:"Pegmatite",pair:"Peridotite",distance:1.9027,similarity:0.4634},
    {ref:"Pegmatite",pair:"Pumice",distance:2.3426,similarity:0.378},
    {ref:"Peridotite",pair:"Andesite",distance:1.2016,similarity:0.5919},
    {ref:"Peridotite",pair:"Basalt",distance:1.3757,similarity:0.5699},
    {ref:"Peridotite",pair:"Diorite",distance:1.8609,similarity:0.4646},
    {ref:"Peridotite",pair:"Gabbro",distance:1.2898,similarity:0.5879},
    {ref:"Peridotite",pair:"Obsidian",distance:1.1124,similarity:0.6261},
    {ref:"Peridotite",pair:"Pegmatite",distance:1.9027,similarity:0.4634},
    {ref:"Peridotite",pair:"Peridotite",distance:1.2056,similarity:0.606},
    {ref:"Peridotite",pair:"Pumice",distance:1.2223,similarity:0.5846},
    {ref:"Pumice",pair:"Andesite",distance:1.0681,similarity:0.6322},
    {ref:"Pumice",pair:"Basalt",distance:1.353,similarity:0.5659},
    {ref:"Pumice",pair:"Diorite",distance:2.3954,similarity:0.3558},
    {ref:"Pumice",pair:"Gabbro",distance:1.6765,similarity:0.4835},
    {ref:"Pumice",pair:"Obsidian",distance:1.3339,similarity:0.5606},
    {ref:"Pumice",pair:"Pegmatite",distance:2.3426,similarity:0.378},
    {ref:"Pumice",pair:"Peridotite",distance:1.2223,similarity:0.5846},
    {ref:"Pumice",pair:"Pumice",distance:0.7732,similarity:0.7082}
];

const survey_JSON = {
  showQuestionNumbers: "off",
  widthMode: "responsive",
  elements: [
    {
      type: "html",
      name: "survey_intro",
      html: "<b>Think about the most recent science class you have taken, which might be a class you are currently taking. Please rate the following items based on your behavior in this class.</b>" +
            "<br><br><span style='color:red'>Note: This survey is for research purposes and will remain confidential. There are no right or wrong answers;" +
            "we are interested in understanding genuine student experiences and perspectives. Please answer truthfully, based on your actual behavior and not what you think is the 'ideal' answer. Your honesty will help in improving educational practices and benefiting future students.</span>"
    },
    {
      type: "matrix",
      name: "",
      alternateRows: true,
      rowTitleWidth: "250px",
      columns: [
        { value: 5, text: "Always" },
        { value: 4, text: "Often" },
        { value: 3, text: "Sometimes" },
        { value: 2, text: "Rarely" },
        { value: 1, text: "Never" }
      ],
      rows: [
        { value: "Q1", text: "I ask myself questions to make sure I know the material I have been studying" },
        { value: "Q2", text: "When work is hard I either give up or study only the easy parts" },
        { value: "Q3", text: "I work on practice exercises and answer end-of-chapter questions even when I don't have to" },
        { value: "Q4", text: "Even when study materials are dull and uninteresting, I keep working until I finish" },
        { value: "Q5", text: "Before I begin studying I think about the things I will need to do to learn" },
        { value: "Q6", text: "I often find that I have been reading for class but don't know what it is all about" },
        { value: "Q7", text: "I find that when the teacher is talking I think of other things and don't really listen to what is being said" },
        { value: "Q8", text: "When I'm reading I stop once in a while and go over what I have read" },
        { value: "Q9", text: "I work hard to get a good grade even when I don't like a class" }
      ],
      rowsOrder: "random",
      isAllRowRequired: true
    }
  ]
};


// for algorithm test
const responses = [
  [
    "Peridotite", "Obsidian", "Basalt", "Pegmatite", "Diorite", "Pumice", "Diorite", "Peridotite", 
    "Peridotite", "Basalt", "Andesite", "Pumice", "Obsidian", "Gabbro", "Andesite", "Obsidian", 
    "Basalt", "Andesite", "Pegmatite", "Basalt", "Gabbro", "Peridotite", "Gabbro", "Pumice"
  ],
  [
    "Basalt", "Pegmatite", "Peridotite", "Gabbro", "Andesite", "Pumice", "Pumice", "Pegmatite", 
    "Pegmatite", "Obsidian", "Gabbro", "Gabbro", "Diorite", "Pumice", "Pegmatite", "Andesite", 
    "Basalt", "Andesite", "Diorite", "Obsidian", "Obsidian", "Diorite", "Gabbro", "Peridotite"
  ],
  [
    "Pumice", "Andesite", "Gabbro", "Peridotite", "Pegmatite", "Basalt", "Peridotite", "Andesite", 
    "Basalt", "Diorite", "Pegmatite", "Obsidian", "Basalt", "Basalt", "Obsidian", "Obsidian", "Andesite", 
    "Pegmatite", "Peridotite", "Pumice", "Gabbro", "Pumice", "Gabbro", "Diorite"
  ],
];

const categories = [
  [
    "Peridotite", "Obsidian", "Basalt", "Peridotite", "Andesite", "Pumice", "Diorite", "Peridotite", 
    "Pegmatite", "Basalt", "Andesite", "Pumice", "Obsidian", "Gabbro", "Diorite", "Obsidian", "Gabbro", 
    "Diorite", "Pegmatite", "Andesite", "Gabbro", "Pegmatite", "Basalt", "Pumice"
  ],
  [
    "Basalt", "Pegmatite", "Pegmatite", "Basalt", "Diorite", "Pumice", "Pumice", "Peridotite", "Peridotite", 
    "Obsidian", "Gabbro", "Gabbro", "Andesite", "Pumice", "Pegmatite", "Andesite", "Basalt", "Andesite", "Diorite", 
    "Obsidian", "Obsidian", "Diorite", "Gabbro", "Peridotite"
  ],
  [
    "Pumice", "Diorite", "Basalt", "Peridotite", "Pegmatite", "Andesite", "Peridotite", "Diorite", "Basalt", 
    "Andesite", "Pegmatite", "Obsidian", "Basalt", "Gabbro", "Obsidian", "Obsidian", "Andesite", "Pegmatite", 
    "Peridotite", "Pumice", "Gabbro", "Pumice", "Gabbro", "Diorite"
  ]
];
